### ISSUE TITLE
FactOnlyOnDebugAttribute no longer working.

### ISSUE THREAD

**Issue by KenVanGilbergen** [Euroconsumers/Euroconsumers.Selenium.Contrib#1]
@kubarom : I moved this thread here, so we do not forget about it.

Kubarom changed implementation to different approach (differently checking debug\release)  but it depends on calling assembly and in context of Xunit calling assembly is Xunit.execution which in turn breaks the algorithm (Kubarom thought that calling assembly would be assembly using FactOnlyOnDebugAttribute - unit test quickly rejected this solution) 

Different possible solution using custom FactDiscoverer.

**Comment by kubarom** [comment]
Resolved in 1b812da4 @ Euroconsumers.Xunit.Contrib
